# Makefile untuk pipeline machine learning

.PHONY: data train evaluate deploy

data:
	python scripts/data_prep.py

train:
	python scripts/train_model.py

evaluate:
	python scripts/evaluate_model.py

deploy:
	python scripts/deploy_model.py
